-- Migration: 20260622_001_content_recap
-- Purpose: Add a short "previously on..." recap to each episode.
--   recap = 2-3 sentence summary of THIS episode, generated by AI in the admin
--   panel and human-reviewed. On the episode page it is shown as "Що було раніше"
--   using the recap of the PREVIOUS episode, lowering the barrier to returning
--   after a pause in a 90+ episode serial.
--
-- nullable: episodes without a recap (first episode overall, or not yet generated)
-- simply do not show the block.

ALTER TABLE public.content
  ADD COLUMN IF NOT EXISTS recap TEXT NULL;

COMMENT ON COLUMN public.content.recap IS
  '2-3 речення «що було в цьому епізоді»; показується на наступному епізоді як «Що було раніше». Генерується AI в адмінці + людська вичитка.';
